# Main tasks for sat-ncn role.
# (C) Copyright 2021 Hewlett Packard Enterprise Development LP.
---
- name: Add SAT zypper repositories
  zypper_repository:
    repo: "{{ item }}"
    name: "{{ item | basename }}"
    disable_gpg_check: yes
  with_items: "{{ sat_repos }}"

- name: Ensure cray-sat-podman is installed
  zypper:
    name: cray-sat-podman
    state: latest
    disable_gpg_check: yes
    disable_recommends: no
    force: yes
    update_cache: yes
